### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by hungdev** [paramoshkinandrew/ReactNativeCircleCheckbox#10]
the fist, i install by using command:   npm install react-native-circle-checkbox --save
its run error. look at the image:
<img width="755" alt="screen shot 2018-01-27 at 8 38 17 pm" src="https://user-images.githubusercontent.com/12009276/35472461-2e872e6e-03a2-11e8-9c26-e4c9c707d508.png">
then i cant run react-native run-android. After that, i run: npm i to install package again. then run react-native run-android again. It says error like image:
<img width="1175" alt="screen shot 2018-01-27 at 8 37 58 pm" src="https://user-images.githubusercontent.com/12009276/35472476-7c9fb24c-03a2-11e8-9b2d-0755d80a6dad.png">

**Comment by hungdev** [comment]
I think the problem is not due to your code. Because i copy your code to new file. it run ok. But when i install to new project, it always errors.

**Comment by paramoshkinandrew** [comment]
@hungdev have you already found the reason of your problem?
I've just tried to repeat your error. 
I created new project with `react native init Test` command, installed CircleCheckbox packaged with `npm install react-native-circle-checkbox --save` command and changed `App` class inside `App.js` with the next content:
```
export default class App extends Component {
  state = {checked: false};

  onToggle = (checked) => this.setState(() => ({checked}));

  render() {
    return (
      <View style={styles.container}>
        <CircleCheckbox 
          checked={this.state.checked} 
          onToggle={this.onToggle} 
          label="Checkbox" 
        />
      </View>
    );
  }
}
``` 
After all I built the project (iOS platform in my case) and got expected result:
 
![image](https://user-images.githubusercontent.com/3299604/35675759-53fa2730-075a-11e8-9273-4194670a206f.png)
![image](https://user-images.githubusercontent.com/3299604/35675812-750c15e6-075a-11e8-9ead-244989ebaa45.png)

**Comment by hungdev** [comment]
I tried with another one computer, but it still error like this.
```
error: bundling failed: ambiguous resolution: module `/Users/so/Documents/workspace/my-app/index.android.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `/Users/so/Documents/workspace/my-app/node_modules/react-native-circle-checkbox/node_modules/react-native/package.json`
  * `/Users/so/Documents/workspace/my-app/node_modules/react-native/package.json`
```
