### ISSUE TITLE
Screenshots Please

### ISSUE THREAD

**Issue by Noitidart** [paramoshkinandrew/ReactNativeCircleCheckbox#11]
May you please add screenshots (ideally GIF) of this in action in readme? That's the first thing a lot of RN package searchers do. There are so many packages its not easy to (1) install each one, (2) then render it respecting properties, (3) then uninstall it if it doesn't fit.

**Comment by paramoshkinandrew** [comment]
Hi there. I’ll make it ASAP. Thank you for advice!

**Comment by Noitidart** [comment]
Thank you so much!

**Comment by paramoshkinandrew** [comment]
@Noitidart Now you can find a gif example of different cases in the package description.

**Comment by Noitidart** [comment]
Ah very cool this is something I needed, thank you!
