### ISSUE TITLE
Checkbox not changing appearance onToggle

### ISSUE THREAD

**Issue by InnovationZone** [paramoshkinandrew/ReactNativeCircleCheckbox#13]
Hi, 

I've installed the component. But When I click on it to Toggle the checkbox, the appearance does not change. If the default value is FALSE, the console.log prints "TRUE" when toggling, so it seems to work but the circle is not filled up.

`<CircleCheckBox
              onToggle={(checked) => console.log('My state is: ', checked)}
              labelPosition={LABEL_POSITION.RIGHT}
              label="Checkbox example"
            />`

Maybe you can help ? 

Thanks in advance !

**Comment by paramoshkinandrew** [comment]
Hi @InnovationZone,

Glad to hear you're using this library)
Could you please provide the code example?
According to your description, you haven't provided `onToggle ` and `checked` props. This component has to be controlled. Other words, you should persist a state, provided by `onToggle` and pass it as `checked` prop.

**Comment by paramoshkinandrew** [comment]
Just a small example of controlled component
```
class App extends React.PureComponent {
	state = { checked: false };

	onToggle = checked => this.setState({ checked });

	render() {
		const { checked } = this.state;
		return (
			<CircleCheckBox
			 	checked={checked}
			 	onToggle={this.onToggle}
				labelPosition={LABEL_POSITION.RIGHT}
				label="Checkbox example"
			/>
		);
	}
}
```

Or with hooks

```

function App() {
	const [checked, setChecked] = React.useState(false);

	return (
		<CircleCheckBox
		 	checked={checked}
		 	onToggle={setChecked}
			labelPosition={LABEL_POSITION.RIGHT}
			label="Checkbox example"
		/>
	);
}
```

**Comment by InnovationZone** [comment]
Thanks a lot !!! It works ! Missed the persist state ;)

**Comment by paramoshkinandrew** [comment]
Awesome! Hope this one will be useful for you)
